import { IAddFilter, IErrorCallback, IFilterSetup, IObserver, ISetup, IStream, ISubscribeGroup, ISubscribeObject, ISubscriptionLike } from "./Types";
import { SubscribeObject } from "./SubscribeObject";
import { FilterCollection } from "./FilterCollection";
export declare class Observable<T> implements IObserver<T>, IStream<T>, IAddFilter<T> {
    protected subs: ISubscribeObject<T>[];
    protected enabled: boolean;
    protected killed: boolean;
    protected process: boolean;
    protected trash: ISubscriptionLike[];
    protected filters: FilterCollection<T>;
    protected _value: T;
    constructor(value: T);
    addFilter(errorHandler?: IErrorCallback): IFilterSetup<T>;
    disable(): void;
    enable(): void;
    get isEnable(): boolean;
    next(value: T): void;
    stream(values: T[]): void;
    private clearTrash;
    unSubscribe(listener: ISubscriptionLike): void;
    destroy(): void;
    unsubscribeAll(): void;
    getValue(): T | undefined;
    size(): number;
    subscribe(observer: ISubscribeGroup<T>, errorHandler?: IErrorCallback): ISubscriptionLike | undefined;
    protected addObserver(subscribeObject: SubscribeObject<T>, observer: ISubscribeGroup<T>, errorHandler?: IErrorCallback): void;
    protected isListener(listener: ISubscribeGroup<T>): boolean;
    pipe(): ISetup<T> | undefined;
    get isDestroyed(): boolean;
}
